#!/bin/bash

# Sets up the host computer to work with the project, if using an Ubuntu based Linux distribution.
if [ "$1" = "init" ]; then
	# Install docker if missing
	if ! which docker &>/dev/null ; then
		echo -e "\e[0;93m⚠️  Missing docker package. Installing...\e[0m"
		sudo curl -sSL https://get.docker.com | sudo sh
		sudo groupadd docker
		sudo usermod -aG docker $USER
		sudo newgrp docker
	fi

	echo "Setup done."
	exit
fi

COMPOSE_ACTION=""

if [ "$1" = "start" ]; then
	COMPOSE_ACTION="up"
elif [ "$1" = "stop" ]; then
	COMPOSE_ACTION="down"
else	
	echo -e "\e[93mℹ️ Unrecognized command.\e[0m"
	exit 1
fi

export PROJECT_DIR=$PWD

if [ "$2" = "--prod" ]; then
	docker compose -f stacks/panel/panel.yml $COMPOSE_ACTION
else
	echo -e "\e[34mℹ️ [ESPHome] the username is 'esphome'.\e[0m"

	if [ -f './secrets/password.key' ]; then
		echo -e "\e[34mℹ️ [ESPHome] Using your custom password from secrets/password.key .\e[0m"
		export ESPHOME_PASSWORD=$(cat ./secrets/password.key )
	else
		echo -e "\e[93mℹ️ [ESPHome] Using default password '1234'.\e[0m"
		export ESPHOME_PASSWORD='1234'
	fi
	docker compose -f stacks/panel/panel.yml -f stacks/panel/panel.dev.yml $COMPOSE_ACTION
fi
