- id: '1686653858189'
  alias: Modo noche
  description: Mantiene el dormitorio a una temperatura decente
  trigger:
  - platform: time_pattern
    seconds: /1
  condition: []
  action:
  - if:
    - condition: numeric_state
      entity_id: sensor.climatizador_del_dormitorio_temperature
      above: 27.5
    - condition: state
      entity_id: climate.climatizador_del_dormitorio_ac
      state: 'off'
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: cool
      target:
        entity_id: climate.climatizador_del_dormitorio_ac
  - if:
    - condition: numeric_state
      entity_id: sensor.climatizador_del_dormitorio_temperature
      below: 27
    - condition: state
      entity_id: climate.climatizador_del_dormitorio_ac
      state: cool
    then:
    - service: climate.turn_off
      data: {}
      target:
        entity_id: climate.climatizador_del_dormitorio_ac
  mode: single
