version: '2.0'
services:
  esphome:
    container_name: esphome
    restart: always
    image: esphome/esphome:2023.3
    volumes:
      - ${PROJECT_DIR}/stacks/panel/esphome/config:/config
      - ${PROJECT_DIR}/stacks/panel/esphome/tweaks/components/mitsubishi:/esphome/esphome/components/mitsubishi
      - ${PROJECT_DIR}/stacks/panel/esphome/tweaks/components/remote_receiver/remote_receiver.h:/esphome/esphome/components/remote_receiver/remote_receiver.h
      - ${PROJECT_DIR}/stacks/panel/esphome/tweaks/dashboard.py:/esphome/esphome/dashboard/dashboard.py
    network_mode: 'host'
    command: dashboard --username esphome --password '${ESPHOME_PASSWORD}' /config
  webserver:
    container_name: panel-webserver
    image: nginx:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
    volumes:
      - ${PROJECT_DIR}/stacks/panel/webserver/default.conf:/etc/nginx/conf.d/default.conf
