version: '2.0'
networks:
  default:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.33.0.0/24"
                gateway: "172.33.0.1"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${PROJECT_DIR}/stacks/panel/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
  webserver:
    container_name: panel-webserver
    image: nginx:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
    volumes:
      - ${PROJECT_DIR}/stacks/panel/webserver/default.conf:/etc/nginx/conf.d/default.conf